# disabled rules
disabled_rules:
    - identifier_name
    - trailing_whitespace
    - trailing_newline
    - line_length
    
# rules we want to apply
opt_in_rules:
    - empty_count
    
# disabling lint for certain dependency manager
excluded:
    - Carthage
    - Pods
    - vendor
    
# modifying some rules

function_body_length:
    warning: 300
    error: 500

#line_lenght:
 #   warning: 150
  #  error: 200

# for disabling some rule in the code
       # // swiftlint:disable empty_count

