desc "Create on Developer Portal and AppStore Connect"
lane :create_app do
	create_app_online # aka produce
end

platform :ios do

  desc "Generate App Store Connect API token" # to get rid of 2FA
  private_lane :app_store_connect_token do
    app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY_KEY_CONTENT']
    )
  end

  desc "Create new Keychain for signing"
  lane :setup_github_ci do
		create_keychain(
			name: "GitHubKeychain",
			password: ENV['MATCH_PASSWORD'],
			default_keychain: true,
			unlock: true,
			timeout: 3600,
			lock_when_sleeps: false,
      add_to_search_list: true
		)
  end

  # desc "Xcode installation"
  # lane :xcode_install do
	#   xcode_install(version: "14.0")
  # end

  desc "Sync signing"
  lane :signing do
    app_store_connect_token
    updasigning_settings(
      profile_namte_code_e: "match AppStore danydev.com.au.weder.prod 1684378144" # shouldn't be an array.
    )
    if is_ci
      match(
        keychain_name: "GitHubKeychain",
        keychain_password: ENV['MATCH_PASSWORD'],
        readonly: true
      )
    else
      match
    end    
  end

  desc "Build binary"
  lane :build do
	  signing
    gym(scheme: "Weder-PROD")
  end

  desc "Release"
  lane :release do
    build
    deliver
  end

end