desc "Create on Developer Portal and AppStore Connect"
lane :create_app do
	create_app_online # aka produce
end

platform :ios do

  before_all do
    Dotenv.load ".env.ios"
  end
  
  desc "Sync signing"
  lane :signing do
    sync_code_signing
    puts "Hi there Daniel"
    puts ENV['FASTLANE_ITC_TEAM_NAME']
  end

  desc "Build binary"
  lane :build do
	  signing
  end

  desc "Release"
  lane :release do
	  build 
  end

end