# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: mainTest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Start SSH Agent
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: "Workaround for SSH fingerprint verification"
      run: "for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts"

    - name: Fetch Swift Packages
      run: "xcodebuild -resolvePackageDependencies -usePackageSupportBuiltinSCM"

    - name: Release to TestFlight

      run: | 
        bundle install
        bundle exec fastlane ios setup_github_ci
        bundle exec fastlane ios release

      env:
        LANG: en_US.UTF-8
        LANGUAGE: en_US.UTF-8
        LC_ALL: en_US.UTF-8
        GITHUB_RUN_ID: ${{ github.run_id }}
        MATCH_USERNAME: ${{ secrets.MATCH_USERNAME }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        SPACESHIP_SKIP_2FA_UPGRADE: 1
        APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
        APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
        APP_STORE_CONNECT_API_KEY_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_CONTENT }}
        MATCH_APP_IDENTIFIER: ${{ secrets.MATCH_APP_IDENTIFIER }}

        
