# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: mainTest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Release to TestFlight

      run: fastlane ios signing
      env:
        LANG: en_US.UTF-8
        LANGUAGE: en_US.UTF-8
        LC_ALL: en_US.UTF-8
        SPACESHIP_SKIP_2FA_UPGRADE: 1
        GITHUB_RUN_ID: ${{ github.run_id }}
        MATCH_USERNAME: ${{ secrets.MATCH_USERNAME }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER: ${{ secrets.DEFAULT_NUMBER }}
