# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: mainTest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: xcodebuild -scheme Weder-TEST
      
    - name: Check Secrets
      run: |
       if ${{ secrets.DANI_TEST }} == "DANI TEST IS TEST"; then 
        echo "secret is";
       else 
        echo "secret is not DANI TEST IS TEST"; 
       fi
        
  check:
      runs-on: [macos-latest]

      steps:
      - name: Check Secrets
        run: |
            if [[ ${{ secrets.STEW_TEST }} == "We are checking the secrets here you idiot" ]]; then 
              echo "secret is connected";
            else 
              echo "secret is not what we want"; 
            fi
